services:
  jellyfin:
    image: 'jellyfin/jellyfin:latest'
    container_name: jellyfin
    user: '1000:1000'
    ports:
      - '8096:8096'
    volumes:
      - './jellyfin/config:/config'
      - './jellyfin/cache:/cache'
      - type: bind
        source: ./jellyfin/media
        target: /media
      - type: bind
        source: ./jellyfin/media2
        target: /media2
        read_only: true
    restart: unless-stopped
    env_file:
      - .env
  deluge:
    image: 'lscr.io/linuxserver/deluge:latest'
    container_name: deluge
    env_file:
      - .env
    volumes:
      - './deluge/config:/config'
      - './jellyfin/media:/downloads'
    ports:
      - '8112:8112'
      - '6881:6881'
      - '6881:6881/udp'
      - '58846:58846'
    restart: unless-stopped
  jackett:
    image: 'linuxserver/jackett:latest'
    container_name: jackett
    ports:
      - '9117:9117'
    volumes:
      - './jackett/config:/config'
      - './downloads:/downloads'
    env_file:
      - .env
    restart: unless-stopped
